## PERSISTANCE STORE FOR EVENTS
EventsStore:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
      - AttributeName: "eventFilter"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: "HASH"
      - AttributeName: "eventFilter"
        KeyType: "RANGE"
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
